id: I4087208E
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:53.787628
last_modified: 2023-01-04 11:28:53.787643
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  99D0:
    title: Prayer for the Long Life of Alak Zenkar Rinpoche
    base_file: 99D0.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
